[theme]
primaryColor = "#0066cc"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#2c3e50"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
address = "0.0.0.0"
port = 8501