
[theme]
primaryColor = "#0066cc"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#2c3e50"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = false

# Load custom CSS
[ui]
customCss = "styles/custom.css"
